export const FRAME_TEXT_STYLES = [
  {
    id: "allura",
    label: "Allura",
    sample: "Allura",
    fontFamily: "'Allura', cursive",
    letterSpacing: "0.04em",
  },
  {
    id: "arial",
    label: "Arial",
    sample: "Arial",
    fontFamily: "Arial, 'Helvetica Neue', sans-serif",
  },
  {
    id: "bebas-neue",
    label: "Bebas Neue",
    sample: "Bebas Neue",
    fontFamily: "'Bebas Neue', sans-serif",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "cinzel",
    label: "Cinzel",
    sample: "Cinzel",
    fontFamily: "'Cinzel', serif",
    textTransform: "uppercase",
    letterSpacing: "0.18em",
  },
  {
    id: "courier-new",
    label: "Courier New",
    sample: "Courier New",
    fontFamily: "'Courier New', Courier, monospace",
    letterSpacing: "0.08em",
  },
  {
    id: "dancing-script",
    label: "Dancing Script",
    sample: "Dancing Script",
    fontFamily: "'Dancing Script', cursive",
    letterSpacing: "0.05em",
  },
  {
    id: "fredoka-one",
    label: "Fredoka One",
    sample: "Fredoka One",
    fontFamily: "'Fredoka One', cursive",
    letterSpacing: "0.05em",
  },
  {
    id: "georgia",
    label: "Georgia",
    sample: "Georgia",
    fontFamily: "Georgia, 'Times New Roman', serif",
  },
  {
    id: "great-vibes",
    label: "Great Vibes",
    sample: "Great Vibes",
    fontFamily: "'Great Vibes', cursive",
    letterSpacing: "0.03em",
  },
  {
    id: "inter",
    label: "Inter",
    sample: "Inter",
    fontFamily: "'Inter', 'Helvetica Neue', Arial, sans-serif",
    textTransform: "uppercase",
    letterSpacing: "0.15em",
  },
  {
    id: "playfair-display",
    label: "Playfair Display",
    sample: "Playfair Display",
    fontFamily: "'Playfair Display', serif",
    textTransform: "uppercase",
    letterSpacing: "0.2em",
  },
  {
    id: "roboto-condensed",
    label: "Roboto Condensed",
    sample: "Roboto Condensed",
    fontFamily: "'Roboto Condensed', sans-serif",
    textTransform: "uppercase",
    letterSpacing: "0.12em",
  },

  {
    id: "times-new-roman",
    label: "Times New Roman",
    sample: "Times New Roman",
    fontFamily: "'Times New Roman', serif",
  },

  {
    id: "verdana",
    label: "Verdana",
    sample: "Verdana",
    fontFamily: "Verdana, 'Geneva', sans-serif",
  },
  {
    id: "bungee-tint",
    label: "Bungee Tint",
    sample: "Bungee Tint",
    fontFamily: "'Bungee Tint', cursive",
    textTransform: "uppercase",
    letterSpacing: "0.12em",
  },
  {
    id: "ewert",
    label: "Ewert",
    sample: "Ewert",
    fontFamily: "'Ewert', cursive",
    textTransform: "uppercase",
    letterSpacing: "0.14em",
  },
  {
    id: "faster-one",
    label: "Faster One",
    sample: "Faster One",
    fontFamily: "'Faster One', cursive",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "flavors",
    label: "Flavors",
    sample: "Flavors",
    fontFamily: "'Flavors', cursive",
    letterSpacing: "0.04em",
  },
  {
    id: "fredericka-the-great",
    label: "Fredericka the Great",
    sample: "Fredericka",
    fontFamily: "'Fredericka the Great', cursive",
    letterSpacing: "0.08em",
  },
  {
    id: "frijole",
    label: "Frijole",
    sample: "Frijole",
    fontFamily: "'Frijole', cursive",
    textTransform: "uppercase",
    letterSpacing: "0.16em",
  },
  {
    id: "henny-penny",
    label: "Henny Penny",
    sample: "Henny Penny",
    fontFamily: "'Henny Penny', cursive",
    letterSpacing: "0.06em",
  },
  {
    id: "honk",
    label: "Honk",
    sample: "Honk",
    fontFamily: "'Honk', system-ui",
    textTransform: "uppercase",
    letterSpacing: "0.1em",
  },
  {
    id: "jacquard-24",
    label: "Jacquard 24",
    sample: "Jacquard 24",
    fontFamily: "'Jacquard 24', system-ui",
    textTransform: "uppercase",
    letterSpacing: "0.12em",
  },
  {
    id: "jacquard-24-charted",
    label: "Jacquard 24 Charted",
    sample: "Jacquard Chart",
    fontFamily: "'Jacquard 24 Charted', system-ui",
    textTransform: "uppercase",
    letterSpacing: "0",
  },
  {
    id: "jacques-francois-shadow",
    label: "Jacques Francois Shadow",
    sample: "Jacques",
    fontFamily: "'Jacques Francois Shadow', serif",
    textTransform: "uppercase",
    letterSpacing: "0.14em",
  },
  {
    id: "kalnia-glaze",
    label: "Kalnia Glaze",
    sample: "Kalnia Glaze",
    fontFamily: "'Kalnia Glaze', serif",
    letterSpacing: "0.06em",
  },
  {
    id: "mea-culpa",
    label: "Mea Culpa",
    sample: "Mea Culpa",
    fontFamily: "'Mea Culpa', cursive",
    letterSpacing: "0.02em",
  },
  {
    id: "modak",
    label: "Modak",
    sample: "Modak",
    fontFamily: "'Modak', cursive",
    textTransform: "uppercase",
    letterSpacing: "0.1em",
  },
  {
    id: "monoton",
    label: "Monoton",
    sample: "Monoton",
    fontFamily: "'Monoton', cursive",
    textTransform: "uppercase",
    letterSpacing: "0.2em",
  },
  {
    id: "nabla",
    label: "Nabla",
    sample: "Nabla",
    fontFamily: "'Nabla', system-ui",
    textTransform: "uppercase",
    letterSpacing: "0.12em",
  },
  {
    id: "neonderthaw",
    label: "Neonderthaw",
    sample: "Neonderthaw",
    fontFamily: "'Neonderthaw', cursive",
    letterSpacing: "0.04em",
  },
  {
    id: "nosifer",
    label: "Nosifer",
    sample: "Nosifer",
    fontFamily: "'Nosifer', cursive",
    textTransform: "uppercase",
    letterSpacing: "0.14em",
  },
  {
    id: "rampart-one",
    label: "Rampart One",
    sample: "Rampart",
    fontFamily: "'Rampart One', cursive",
    textTransform: "uppercase",
    letterSpacing: "0.1em",
  },
  {
    id: "rubik-doodle-shadow",
    label: "Rubik Doodle Shadow",
    sample: "Rubik Shadow",
    fontFamily: "'Rubik Doodle Shadow', system-ui",
    letterSpacing: "0.06em",
  },
  {
    id: "rubik-scribble",
    label: "Rubik Scribble",
    sample: "Rubik Scribble",
    fontFamily: "'Rubik Scribble', system-ui",
    letterSpacing: "0.04em",
  },
  {
    id: "rye",
    label: "Rye",
    sample: "Rye",
    fontFamily: "'Rye', cursive",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "splash",
    label: "Splash",
    sample: "Splash",
    fontFamily: "'Splash', cursive",
    letterSpacing: "0.03em",
  },
  {
    id: "style-script",
    label: "Style Script",
    sample: "Style Script",
    fontFamily: "'Style Script', cursive",
    letterSpacing: "0.02em",
  },
  {
    id: "tapestry",
    label: "Tapestry",
    sample: "Tapestry",
    fontFamily: "'Tapestry', cursive",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  {
    id: "tiktok-sans",
    label: "TikTok Sans",
    sample: "TikTok Sans",
    fontFamily: "'TikTok Sans', sans-serif",
    letterSpacing: "0.04em",
    styleOverrides: {
      fontVariationSettings: "'opsz' 24",
    },
  },
  {
    id: "tilt-prism",
    label: "Tilt Prism",
    sample: "Tilt Prism",
    fontFamily: "'Tilt Prism', cursive",
    textTransform: "uppercase",
    letterSpacing: "0.16em",
  },
];

export function getFrameTextStyle(styleId = "allura") {
  return (
    FRAME_TEXT_STYLES.find((style) => style.id === styleId) ??
    FRAME_TEXT_STYLES[0]
  );
}

export const FRAME_TEXT_COLORS = [
  { id: "slate", label: "Slate", value: "#475569" },
  { id: "charcoal", label: "Charcoal", value: "#1f2933" },
  { id: "white", label: "White", value: "#ffffff" },
  { id: "soft-gold", label: "Soft Gold", value: "#f6c56c" },
  { id: "rose", label: "Rose", value: "#f472b6" },
  { id: "mint", label: "Mint", value: "#34d399" },
  { id: "azure", label: "Azure", value: "#38bdf8" },
  { id: "violet", label: "Violet", value: "#c084fc" },
];

export function getFrameTextColor(colorId = "slate") {
  return (
    FRAME_TEXT_COLORS.find((color) => color.id === colorId) ??
    FRAME_TEXT_COLORS[0]
  );
}
